groups:
    - developers
recipes:
    mac_os_x:
        - osxdefaults::set_computer_name
attributes:
    osxdefaults:
        computername: brian-mbp
    homebrewalt:
        apps:
            - git-extras
        cask_apps:
            - sourcetree