groups:
    - developers
recipes:
    mac_os_x:
        - osxdefaults::set_computer_name
attributes:
    osxdefaults:
        computername: brian-mbp
    authorization:
        sudo:
            users:
                - brian
            passwordless: true
            include_sudoers_d: true
    homebrewalt:
        apps:
            - git-extras
        cask_apps:
            - sourcetree
    oh_my_zsh:
        users:
            -
                login: brian
                home: /Users/brian


