recipes:
    global:
        - dotfiles::gitconfig
        - applications::ssh_config
        - dotfiles::vim
        - dotfiles::workspace
    mac_os_x:
        - applications::sublime_text_3
        - applications::gnu-tar
        - applications::gems
attributes:
    homebrewalt:
        apps:
            - git
            - git-extras
            - wget
            - pwgen
            - xmlstarlet
            - pv
            - htop-osx
            - git-flow
            - watch
            # requires brew link pcre
            - nginx
            - sbt
        cask_apps:
            - evernote
            - vagrant
            - virtualbox
            - intellij-idea-ce
            - java
            - chefdk
            - gulp
            - mongodb
            - node
            - skitch
            - snagit
            - tunnelblick
    nodejs:
        apps:
            - bower
            - grunt
            - grunt-cli
            - gulp
            - coffee-script
            - browser-sync
    gems:
        - sass
        - compass
    oh_my_zsh:
        theme: ys
        plugins:
            - brew
            - osx
            - bundler
            - gem
            - node
            - npm
            - scala
            - sbt
            - vagrant
            - knife
            - knife_ssh
            - github
            - git
            - coffee
            - themes

